version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - dogsled
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
    # Added linters
    - godot
    - godoclint
    - dupword
    - errorlint
    - nilerr
  settings:
    gocyclo:
      min-complexity: 15
    revive:
      enable-all-rules: false
      rules:
        - name: var-naming
          disabled: true
    godot:
      scope: toplevel
